org:
  quartz:
    scheduler:
      instanceName: PostToChatwork
      instanceId: AUTO
    threadPool:
      threadCount: 5
job:
  startDelay: 0
  repeatInterval: 60000
  description: Post to chatwork job
  key: StatisticsJob